### ISSUE TITLE
Installation clarification

### ISSUE THREAD

**Issue by xpe** [joshuafcole/claire#13]
Questions:
- Should installing Claire from inside of Light Table work? (The instructions only mention a command line installation.)
- Does installing Claire from inside of Light Table install [claire-files](https://github.com/joshuafcole/claire-files)?
- Is `claire-files` required? Why? People new to Light Table (such as me) may not see why a back-end is needed. Why is a back-end needed?

**Comment by joshuafcole** [comment]
Hey xpe, claire comes pre-bundled with all dependencies in the LT repo. Unfortunately, it does not yet support the atom-shell branch, due to a very different node interface (claire is written in js rather than cljs, since it predates the open sourcing). If you're having any issues besides that, feel free to give me as much information as you can and I'd be glad to help you debug.

**Comment by xpe** [comment]
@joshuafcole There is a bit of a language/experience barrier here. I'm having a hard time translating what you wrote into specific answers to my 3 questions (above).  Could you answer them directly, please?

Here are an additional 3 things that I didn't understand about what you wrote:
- I don't know what "claire comes pre-bundled with all dependencies in the LT repo" means, since I don't know what you mean by the "LT repo". I downloaded LT from lighttable.com, then I used the plugin manager to install Claire. I don't know if this connects or does not connect to what you wrote above.
- I don't know what the atom-shell branch is.
- I don't know the history of what LT was like before it was open source.

**Comment by joshuafcole** [comment]
Claire requires nothing but installing it via the plugin manager if you're
using the current stable binary of Light Table.

Cheers,
Josh

On Sun, Feb 15, 2015 at 1:44 PM, David James notifications@github.com
wrote:

> joshuafcole: There is a bit of a language barrier here. I'm having a hard
> time translating what you wrote into specific answers to my questions.
> Could you answer them directly?
> - I don't know what "claire comes pre-bundled with all dependencies in
>   the LT repo" means.
> - I don't know what the atom-shell branch is.
> - I don't know the history of what LT was like before it was open
>   source.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joshuafcole/claire/issues/13#issuecomment-74438796.

## 

Screw the environment. Please print this email immediately. And then burn
it.

**Comment by xpe** [comment]
Thanks for your work on this plugin! Based on what you said, here are my guesses as to my remaining questions:

> Does installing Claire from inside of Light Table install claire-files?

Yes

> Is claire-files required?

Yes

> Why? People new to Light Table (such as me) may not see why a back-end is needed. Why is a back-end needed?

I don't know the answer to this.

Corrections and/or explanations would help. I volunteered to talk about Light Table at a user group meeting (if we don't get snowed out), including its architecture, and plugins at a user group meeting. I'll be sharing what I find.

**Comment by joshuafcole** [comment]
Separating claire (the LT interface) from claire-files (the file searching
backend) was just an implementation decision. It made it possible to use
claire-files searching algorithm in other places, if I so chose, and to
integrate the claire frontend with other search algorithms (e.g. one for LT
commands, or any other source of data) with minimal effort. LT itself
imposes no structure on plugins other than the plugin.edn/plugin.json file
entrypoint. The majority of plugins are written in cljs now (claire and
recall were written before LT was opensourced, so interacted with the
compiled JS). If you're interested in learning more about LT plugin
development, I'd be happy to point you in the right direction!

Cheers,
Josh

On Mon, Feb 16, 2015 at 8:15 AM, David James notifications@github.com
wrote:

> Thanks. Based on what you said, here are my guesses as to my remaining
> questions:
> 
> Does installing Claire from inside of Light Table install claire-files?
> 
> Yes
> 
> Is claire-files required?
> 
> Yes
> 
> Why? People new to Light Table (such as me) may not see why a back-end is
> needed. Why is a back-end needed?
> 
> I don't know the answer to this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joshuafcole/claire/issues/13#issuecomment-74532585.

## 

Screw the environment. Please print this email immediately. And then burn
it.

**Comment by xpe** [comment]
Thanks for clearing that up.
