### ISSUE TITLE
README typo?

### ISSUE THREAD

**Issue by shamrin** [joshuafcole/claire#3]
Is something missing?

> Interact by typing. is bound to smart-delete by default, is bound to smart-complete, and opens the current search term.

**Comment by joshuafcole** [comment]
Ah, good catch. I surrounded the shortcuts in less than and greater than signs which I'm familiar with from emacs. Didn't pause to consider they'd get handled funnily in gfm. I'll get that fixed, thanks!

**Comment by joshuafcole** [comment]
Fixed in latest.
