### ISSUE TITLE
Not triggering

### ISSUE THREAD

**Issue by houshuang** [joshuafcole/claire#5]
I pulled it from github head, and installed claire-files. It shows up as installed in my plugin manager, but when I do C-x C-f, it just shows the built-in file selector. Version 0.6.0, binary 0.8.4.

**Comment by joshuafcole** [comment]
If you're using emacs mode, you may need to unbind ctrl-x ctrl-f from the existing navigate-workspace command.

``` lisp
{:- {
  :editor.keys.emacs {
    "ctrl-x ctrl-f" []}}}
```

should suffice. Can you try that and let me know if it's still not working?

**Comment by joshuafcole** [comment]
Also, if you're running from github master, you'll need to manually npm i in the claire plugin directory (it has several deps besides claire-files). If you pull from release, those deps come prebundled.

**Comment by houshuang** [comment]
Thanks, I tried deleting and redownloading through plugin manager, removed
the EMacs plugin, and inserted the unbinding that you mentioned... I even
deleted the Emacs plugin from the plugin directory, but if I press C-x it
still says "C-x mode", and C-f brings up the file menu. Not sure what I'm
doing wrong.

On Tue, Jan 14, 2014 at 1:48 PM, joshuafcole notifications@github.comwrote:

> Also, if you're running from github master, you'll need to manually npm i
> in the claire plugin directory (it has several deps besides claire-files).
> If you pull from release, those deps come prebundled.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joshuafcole/claire/issues/5#issuecomment-32294099
> .

## 

http://reganmian.net/blog -- Random Stuff that Matters

**Comment by houshuang** [comment]
(Really wish Clojure worked like Emacs where every single command was
available in the command buffer, and I could use C-space claire-open or
something like that to open the menu regardless of keyboard binding ... :))

On Tue, Jan 14, 2014 at 1:56 PM, Stian Håklev shaklev@gmail.com wrote:

> Thanks, I tried deleting and redownloading through plugin manager, removed
> the EMacs plugin, and inserted the unbinding that you mentioned... I even
> deleted the Emacs plugin from the plugin directory, but if I press C-x it
> still says "C-x mode", and C-f brings up the file menu. Not sure what I'm
> doing wrong.
> 
> On Tue, Jan 14, 2014 at 1:48 PM, joshuafcole notifications@github.comwrote:
> 
> > Also, if you're running from github master, you'll need to manually npm i
> > in the claire plugin directory (it has several deps besides claire-files).
> > If you pull from release, those deps come prebundled.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/joshuafcole/claire/issues/5#issuecomment-32294099
> > .
> 
> ## 
> 
> http://reganmian.net/blog -- Random Stuff that Matters

## 

http://reganmian.net/blog -- Random Stuff that Matters

**Comment by joshuafcole** [comment]
Actually, that's claire's fault rather than LT's! Claire was built before
LT was open sourced, so I wasn't sure how to tap into the command pipeline.
That'll be fixed tonight or tomorrow. Claire may rely on chording being
turned off, which is set in the emacs behaviors. I'm actually running the
emacs behaviors in conjunction with claire, so it ought to work that way.
Can you try opening the dev-inspector:

(open the commandbar and type 'dev-inspector', and hit enter. No results
will show up because it is a hidden command. It should still work). Then go
to the console tab and type

``` javascript
lt.user_plugins.claire
```

and see if it's registered there?

If so, try

``` javascript
lt.user_plugins.claire.show()
```

If that works, then the issue is with keybinding and we can diagnose that
further. If not, the issue is with the claire installation.

Cheers.

On Tue, Jan 14, 2014 at 10:57 AM, Stian Håklev notifications@github.comwrote:

> (Really wish Clojure worked like Emacs where every single command was
> available in the command buffer, and I could use C-space claire-open or
> something like that to open the menu regardless of keyboard binding ...
> :))
> 
> On Tue, Jan 14, 2014 at 1:56 PM, Stian Håklev shaklev@gmail.com wrote:
> 
> > Thanks, I tried deleting and redownloading through plugin manager,
> > removed
> > the EMacs plugin, and inserted the unbinding that you mentioned... I
> > even
> > deleted the Emacs plugin from the plugin directory, but if I press C-x
> > it
> > still says "C-x mode", and C-f brings up the file menu. Not sure what
> > I'm
> > doing wrong.
> > 
> > On Tue, Jan 14, 2014 at 1:48 PM, joshuafcole notifications@github.comwrote:
> > 
> > > Also, if you're running from github master, you'll need to manually npm
> > > i
> > > in the claire plugin directory (it has several deps besides
> > > claire-files).
> > > If you pull from release, those deps come prebundled.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/joshuafcole/claire/issues/5#issuecomment-32294099>
> > > .
> > 
> > ## 
> > 
> > http://reganmian.net/blog -- Random Stuff that Matters
> 
> ## 
> 
> http://reganmian.net/blog -- Random Stuff that Matters
> 
> —
> 
> Reply to this email directly or view it on GitHubhttps://github.com/joshuafcole/claire/issues/5#issuecomment-32295027
> .

## 

Screw the environment. Please print this email immediately. And then burn
it.

**Comment by houshuang** [comment]
So that's the equivalent to M-x :) Yes, it does indeed show up! So clearly
installed.

**Comment by joshuafcole** [comment]
Yep, I've actually bound the commandbar to M-x via
 `:show-commandbar-transient`. :) In that case there's an issue with the
default keybindings or an interaction with your user keybindings. Can you
please post your full user keybindings?

On Tue, Jan 14, 2014 at 11:45 AM, Stian Håklev notifications@github.comwrote:

> So that's the equivalent to M-x :) Yes, it does indeed show up! So clearly
> installed.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joshuafcole/claire/issues/5#issuecomment-32299995
> .

## 

Screw the environment. Please print this email immediately. And then burn
it.

**Comment by houshuang** [comment]
On Tue, Jan 14, 2014 at 3:01 PM, joshuafcole notifications@github.comwrote:

> :show-commandbar-transient

Is there a way to show the full "computed" keybindings, or do I have to
post the contents of user-keybindings, default-keybindings etc?

## 

http://reganmian.net/blog -- Random Stuff that Matters

**Comment by joshuafcole** [comment]
Not currently, but that'd be a really nice plugin for diagnostic purposes.
:) For now a list of the plugins you have installed and the content of your
user.keymap is the best diagnostics you can provide.

On Tue, Jan 14, 2014 at 12:06 PM, Stian Håklev notifications@github.comwrote:

> On Tue, Jan 14, 2014 at 3:01 PM, joshuafcole <notifications@github.com
> 
> > wrote:
> > 
> > :show-commandbar-transient
> 
> Is there a way to show the full "computed" keybindings, or do I have to
> post the contents of user-keybindings, default-keybindings etc?
> 
> ## 
> 
> http://reganmian.net/blog -- Random Stuff that Matters
> 
> —
> 
> Reply to this email directly or view it on GitHubhttps://github.com/joshuafcole/claire/issues/5#issuecomment-32301938
> .

## 

Screw the environment. Please print this email immediately. And then burn
it.

**Comment by joshuafcole** [comment]
The 0.1.0 version of claire is nearly finished, and will package claire using actual LT commands instead of CM actions. That should hopefully make it more robust and ensure this is just a keymap issue instead of some particular platform/versioning issue.
