### ISSUE TITLE
search bar disappears after toggling console

### ISSUE THREAD

**Issue by cldwalker** [joshuafcole/claire#6]
Hi,

I noticed with the latest Claire and LT, 0.1.5 and 0.6.2, that "Show Claire search bar" functionality stops appearing after I toggle the console on and off once. Is this expected? If so, is there a workaround?

Thanks for your plugin. It's been handy!

**Comment by joshuafcole** [comment]
I was hoping that was only happening in my latest code -- I recently ran
into it as well. I have a strong hunch as to what's happening, I just
haven't come up with a good way to resolve it yet. I'll be working on this
tonight and will keep you up to date.

Thanks for reporting,
Josh

On Thu, Jan 23, 2014 at 10:48 PM, Gabriel Horner
notifications@github.comwrote:

> Hi,
> 
> I noticed with the latest Claire and LT, 0.1.5 and 0.6.2, that "Show
> Claire search bar" functionality stops appearing after I toggle the console
> on and off once. Is this expected? If so, is there a workaround?
> 
> Thanks for your plugin. It's been handy!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joshuafcole/claire/issues/6
> .

## 

Screw the environment. Please print this email immediately. And then burn
it.

**Comment by joshuafcole** [comment]
Also, as an awful workaround if you open the console directly into a
separate tab then the problem does not surface. It seems to be a conflict
with the way I'm toggling open and closed the bottom bar and the way the
console does so.

On Fri, Jan 24, 2014 at 10:47 AM, Josh Cole joshuafcole@gmail.com wrote:

> I was hoping that was only happening in my latest code -- I recently ran
> into it as well. I have a strong hunch as to what's happening, I just
> haven't come up with a good way to resolve it yet. I'll be working on this
> tonight and will keep you up to date.
> 
> Thanks for reporting,
> Josh
> 
> On Thu, Jan 23, 2014 at 10:48 PM, Gabriel Horner <notifications@github.com
> 
> > wrote:
> > 
> > Hi,
> > 
> > I noticed with the latest Claire and LT, 0.1.5 and 0.6.2, that "Show
> > Claire search bar" functionality stops appearing after I toggle the console
> > on and off once. Is this expected? If so, is there a workaround?
> > 
> > Thanks for your plugin. It's been handy!
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/joshuafcole/claire/issues/6
> > .
> 
> ## 
> 
> Screw the environment. Please print this email immediately. And then burn
> it.

## 

Screw the environment. Please print this email immediately. And then burn
it.

**Comment by seancorfield** [comment]
That workaround doesn't work if you've already opened the console the regular way, as I just found out :(

**Comment by joshuafcole** [comment]
Sorry guys, I'll get to this patched up tonight. It shouldn't be too tough.

On Mon, Jan 27, 2014 at 11:54 AM, Sean Corfield notifications@github.comwrote:

> That workaround doesn't work if you've already opened the console the
> regular way, as I just found out :(
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joshuafcole/claire/issues/6#issuecomment-33413857
> .

## 

Screw the environment. Please print this email immediately. And then burn
it.

**Comment by joshuafcole** [comment]
Now fixed in latest, sorry for the delay. 0.1.6 is up.

**Comment by cldwalker** [comment]
Verified. Thanks!
