### ISSUE TITLE
Editor does not have focus after loading file

### ISSUE THREAD

**Issue by seancorfield** [joshuafcole/claire#7]
When I load a file with Claire, nothing seems to have focus. That means I need to click in the newly opened editor in order to do anything. Can Claire set focus to the newly opened editor so we don't need to take our hands off the keyboard?

**Comment by joshuafcole** [comment]
Ah, good catch. Not sure how I didn't notice that. Yeah, that should
definitely be doable. I'll look into that tonight. Thanks for reporting!

On Mon, Jan 27, 2014 at 3:42 PM, Sean Corfield notifications@github.comwrote:

> When I load a file with Claire, nothing seems to have focus. That means I
> need to click in the newly opened editor in order to do anything. Can
> Claire set focus to the newly opened editor so we don't need to take our
> hands off the keyboard?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joshuafcole/claire/issues/7
> .

## 

Screw the environment. Please print this email immediately. And then burn
it.

**Comment by joshuafcole** [comment]
I'd like to sincerely apologize for the delay. These were tiny fixes but I just haven't had much time to maintain my side projects working at a startup. I plan to set aside some time every weekend to ensure this sort of wait doesn't happen again.

**Comment by seancorfield** [comment]
Dude, it's free open source - don't apologize or feel guilty for the time taken! Claire's great as-is. Updates are gravy. Thank you!
